name: "Frontend Asset Injector"
version: "0.0.9"
slug: "asset_injector"
description: "Injects custom static assets into Home Assistant frontend"
startup: once
boot: manual
host_network: true
init: false
url: "https://github.com/Voyanti/soluno-branding-addon"
arch:
  - aarch64
  - amd64
host_docker: true
privileged:
  - SYS_ADMIN
  - DAC_READ_SEARCH