name: "Frontend Asset Injector"
version: "0.1.2"
slug: "asset_injector"
description: "Injects custom static assets into Home Assistant frontend"
startup: once
boot: manual
host_network: true
init: false
apparmor: false
url: "https://github.com/Voyanti/soluno-branding-addon"
arch:
  - aarch64
  - amd64
host_docker: true
privileged:
  - SYS_ADMIN
  - DAC_READ_SEARCH
  - SYS_RAWIO
maps:
  - "/var/run/docker.sock:/var/run/docker.sock:ro"
  - "/proc/:/host/proc/:ro"
  - "/sys/fs/cgroup/:/host/sys/fs/cgroup:ro"
docker_api: true
host_ipc: true
host_dbus: true
host_pid: true
full_access: true
devices:
  - /var/run/docker.sock:/var/run/docker.sock