name: "Frontend Asset Injector"
version: "0.0.1"
slug: "asset_injector"
description: "Injects custom static assets into Home Assistant frontend"
startup: once
boot: manual
host_network: true
init: false
url: "https://github.com/Voyanti/soluno-branding-addon"
arch:
  - aarch64
  - amd64
privileged:
  - SYS_ADMIN
  - DAC_READ_SEARCH
  - DAC_OVERRIDE
  - FOWNER
  - FSETID
  - SETFCAP
  - SETGID
  - SETUID
  - MKNOD
  - CHOWN
  - NET_ADMIN
  - SYS_PTRACE